apiVersion: v1
kind: Service
metadata:

  name: ingress-svc

  labels:
    app: ingress-svc

spec:

  type: LoadBalancer
  ports:

  - port:       80
    targetPort: 80
    name:       http

  - port:       443
    targetPort: 443
    name:       https

  selector:
    k8s-app: ingress-controller
