apiVersion: v1
kind: Service
metadata:

  namespace:  frontend
  name:       frontend-lb-svc

  labels:
    app: frontend-lb-svc

spec:

  type: LoadBalancer
  ports:

  - port:       80
    targetPort: 80
    name:       http

  - port:       443
    targetPort: 443
    name:       https

  selector:
    k8s-app: frontend-lb-controller

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:

  namespace:  frontend
  name:       loadbalancer-ingress

  annotations:

    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"

spec:
  tls:
  
  - hosts:
    - streamnvr.com
    secretName: tls-streamnvr.com
  
  - hosts:
    - www.streamnvr.com
    secretName: tls-www.streamnvr.com
  
  - hosts:
    - platform.streamnvr.com
    secretName: tls-platform.streamnvr.com
    
  - hosts:
    - support.streamnvr.com
    secretName: tls-support.streamnvr.com

  - hosts:
    - cloud.streamnvr.com
    secretName: tls-cloud.streamnvr.com

  - hosts:
    - devops.streamnvr.com
    secretName: tls-devops.streamnvr.com

  - hosts:
    - monitoring.streamnvr.com
    secretName: tls-monitoring.streamnvr.com

  - hosts:
    - vpn.streamnvr.com
    secretName: tls-vpn.streamnvr.com

  rules:

  - host: streamnvr.com
    http:
      paths:
      - path: /
        backend:
          serviceName: corpwww
          servicePort: 80
  
  - host: www.streamnvr.com
    http:
      paths:
      - path: /
        backend:
          serviceName: corpwww
          servicePort: 80
        
  - host: platform.streamnvr.com
    http:
      paths:
      - path: /
        backend:
          serviceName: corpwww
          servicePort: 80
        
  - host: support.streamnvr.com
    http:
      paths:
      - path: /
        backend:
          serviceName: corpwww
          servicePort: 80
        
  - host: cloud.streamnvr.com
    http:
      paths:
      - path: /
        backend:
          serviceName: corpwww
          servicePort: 80
        
  - host: monitoring.streamnvr.com
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoringwww
          servicePort: 80
        
  - host: vpn.streamnvr.com
    http:
      paths:
      - path: /
        backend:
          serviceName: corpwww
          servicePort: 80